### ISSUE TITLE
Speed Test Issues / Errors Running SpeedTest In Docker

### ISSUE THREAD

**Issue by Sievers79** [MiguelNdeCarvalho/speedtest-exporter#109]
This is being ran as part of the Internet-Pi .. but definatly seems to be an issue with the SpeedTest... or possibly something else.  Here is what I've posted on that repo:
-------------------------------------------------------------------------

I've been troubleshooting why my speed test has been coming up so spotty and inaccurate.  I have been pulling 650 to 950 on the regular speedtest on my laptop.  

Once first started it will hit 800 Mbps(ish).. then drops rappidly....

Running:    sudo docker exec -it internet-monitoring_speedtest_1 speedtest -v

   Speedtest by Ookla

[warning] Receive error: 104 (Connection reset by peer)
[error] Error: [0] Cannot read:
[warning] Write error: 32 (Broken pipe)
[warning] Receive error: 104 (Connection reset by peer)
[warning] Timeout occurred in connect.
[error] Error: [0] Cannot open socket

    Latency:     7.34 ms   (2.24 ms jitter)
   Download:   648.97 Mbps [\                   ]  0%

After It has finished:

   Speedtest by Ookla

    Latency:     6.20 ms   (1.98 ms jitter)
[warning] Receive error: 11 (Resource temporarily unavailable)
[warning] Receive error: 11 (Resource temporarily unavailable)
[warning] Receive error: 11 (Resource temporarily unavailable)
[warning] Receive error: 11 (Resource temporarily unavailable)
[warning] Receive error: 11 (Resource temporarily unavailable)
   Download: FAILED
[error] Cannot read:

I've tried running.. but this didn't seem to work.
docker run -d --network host --name speedtest-exporter miguelndecarvalho/speedtest-exporter:v3.1

** FYI I removed the Server Info / Location above **

**Comment by Sievers79** [comment]
Also to note.. off of a laptop (WIFI 6 not Ethernet like the Pi) I'm getting 931 / 61.... directly from the router I'm getting 917 / 62.  

Any help is greatly appreciated.

**Comment by MiguelNdeCarvalho** [comment]
Hey,

Is it possible for you to test with the latest version please? `3.4.0`

Thanks,
MiguelNdeCarvalho

**Comment by Sievers79** [comment]
Sorry for the late reply.   I have tried this with both:

docker run -d --network host --name speedtest-exporter miguelndecarvalho/speedtest-exporter:v3.4.0

And

docker run -d --network host --name speedtest-exporter miguelndecarvalho/speedtest-exporter:latest

Same results.

I'm going to try to set this up on a different switch and see if I get the same results.... Even possibly switch out PIs to rule out hardware / network.

**Comment by MiguelNdeCarvalho** [comment]
Hey,

No problem, why are you running the container with host network? Try with the a different switch if you can please.

Thanks,
MiguelNdeCarvalho

**Comment by Sievers79** [comment]
Tried it on another switch... same quick drop in speed and errors.   This is my first time using containers... I guess I found this to work..  I've tried with how the Internet Monitoring Pi Project runs it direct as well with the same results.   I also now have tried it without the host network switch... and still results in the same quick drop and errors.

I've been testing using this:  sudo docker exec -it internet-monitoring_speedtest_1 speedtest -v

It seems like something is throttling and killing the connection as it will start at the 300 to 400s and go down to 0 quickly.

I'm going to try to bypass my router (which I've verified QOS and other monitoring is off on), as well as trying a different pi.

**Comment by Sievers79** [comment]
Cleared the static IP of the PI and ran it direct from my Cable Modem... works just fine.   Any known issues with Asus routers that you know of?

**Comment by Sievers79** [comment]
So testing with different static IPs I get the error.. using dynamic... it works fine.

**Comment by Sievers79** [comment]
I ended up leaving the pi to pull DHCP from the router... and set the router to assign the IP.  Its working now.   Seems like a bug when the PI has a static IP set in the GUI.

**Comment by MiguelNdeCarvalho** [comment]
Hey,

Sorry for late response but that's good to know that it is working fine now! I will close the issue, but feel free to reopen if needed!

Thanks,
MiguelNdeCarvalho
