### ISSUE TITLE
Typo in documentation for manual install

### ISSUE THREAD

**Issue by EmilianoMaina** [MiguelNdeCarvalho/speedtest-exporter#118]
Hello,

in the documentation for manual installation ([here](https://docs.miguelndecarvalho.pt/projects/speedtest-exporter/)) there is a minor typo:

It is written:

`Install python modules - pip install -r requirements.tx`

While it should be this to work properly:

`Install python modules - pip install -r src/requirements.tx`

**Comment by MiguelNdeCarvalho** [comment]
Hey,

Really thanks for pointing me out!

Thanks,
MiguelNdeCarvalho
