### ISSUE TITLE
Runtime error to do with logging?

### ISSUE THREAD

**Issue by cliff-wakefield** [MiguelNdeCarvalho/speedtest-exporter#121]
# docker run -p 9798:9798 miguelndecarvalho/speedtest-exporter
Traceback (most recent call last):
  File "/app/exporter.py", line 4, in <module>
    import logging
  File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
    _startTime = time.time()
PermissionError: [Errno 1] Operation not permitted

**Comment by cliff-wakefield** [comment]
This seems to happen when the image is running on a raspberry pi 3b.

Works fine on an Intel Mac.

**Comment by cliff-wakefield** [comment]
Maybe related to https://github.com/docker-library/python/issues/674

**Comment by cliff-wakefield** [comment]
Seems it may have been related to the version of Raspbian I was running I was on buster and I am now on bullseye and things seem to be healthier.

**Comment by MiguelNdeCarvalho** [comment]
Hey,

Thanks for you kind of a contribution, in which architecture where you running it?

Thanks,
MiguelNdeCarvalho

**Comment by cliff-wakefield** [comment]
I was trying to run the container as part of https://github.com/geerlingguy/internet-pi.

I was running this originally on a Raspberry Pi 3b running Raspbian (Buster), now running Raspbian (Bullseye).

**Comment by MiguelNdeCarvalho** [comment]
Can you give me the output of `uname -m` please? Thanks

**Comment by cliff-wakefield** [comment]
```
pi@pi3:~ $ uname -m
armv7l
```

**Comment by MiguelNdeCarvalho** [comment]
I have tried the image in my Pi running Ubuntu 22.04 64Bit and I haven't had that problem, it should be related to Raspbian and 32 bit ARM. Thanks!

**Comment by cliff-wakefield** [comment]
Yeah seems pretty niche and not related to your code ;)

**Comment by MiguelNdeCarvalho** [comment]
Yap, feel free to open if needed again!
