### ISSUE TITLE
io timeout

### ISSUE THREAD

**Issue by StinkyTACO** [MiguelNdeCarvalho/speedtest-exporter#157]
when i try to add a data source I keep getting this same error any pointers?
<img width="893" alt="image" src="https://user-images.githubusercontent.com/35038928/180628769-a2c30c74-6773-436e-957d-339c479a14b1.png">

**Comment by StinkyTACO** [comment]
bump

**Comment by MiguelNdeCarvalho** [comment]
Hey,

@StinkyTACO sorry for the late response, it is giving you a timeout, because you need a Prometheus instance to scrape the metrics from Speedtest-Exporter and then Grafana gets the information from Prometheus not from the Exporter.

Thanks,
MiguelNdeCarvalho

**Comment by StinkyTACO** [comment]
Where can i do that through the UI?

**Comment by StinkyTACO** [comment]
I believe i dont have access to the files in the container or atleast they arent in a directory
