### ISSUE TITLE
speed test not running. 

### ISSUE THREAD

**Issue by jfmanamtr** [MiguelNdeCarvalho/speedtest-exporter#18]
OS is Ubuntu 20.04 running Docker version 19.03.12, build 48a66213fe. 

I have tried this inside & outside of rancher, but the same error shows up in the logs. 

Successfully started Speedtest Exporter on http://localhost:9112
Traceback (most recent call last):
  File "src/exporter.py", line 59, in <module>
    run(PORT, SLEEP)
  File "src/exporter.py", line 48, in run
    test = run_speedtest()
  File "src/exporter.py", line 29, in run_speedtest
    output = subprocess.check_output(cmd)
  File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['speedtest', '--format=json-pretty', '--progress=no', '--accept-license', '--accept-gdpr']' returned non-zero exit status 2.
Successfully started Speedtest Exporter on http://localhost:9112
[2020-10-05 15:36:53.716] [error] Trying to get interface information on non-initialized socket.
Traceback (most recent call last):
  File "src/exporter.py", line 59, in <module>
    run(PORT, SLEEP)
  File "src/exporter.py", line 48, in run
    test = run_speedtest()
  File "src/exporter.py", line 29, in run_speedtest
    output = subprocess.check_output(cmd)
  File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['speedtest', '--format=json-pretty', '--progress=no', '--accept-license', '--accept-gdpr']' returned non-zero exit status 2.
Successfully started Speedtest Exporter on http://localhost:9112

when I go to http://<ip_of_node>:9112, I get this:

# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 274.0
python_gc_objects_collected_total{generation="1"} 66.0
python_gc_objects_collected_total{generation="2"} 0.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 35.0
python_gc_collections_total{generation="1"} 3.0
python_gc_collections_total{generation="2"} 0.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="8",patchlevel="6",version="3.8.6"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 2.2618112e+07
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.6310272e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.60191257567e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.8
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 8.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP speedtest_ping_latency_milliseconds Speedtest current Ping in ms
# TYPE speedtest_ping_latency_milliseconds gauge
speedtest_ping_latency_milliseconds 0.0
# HELP speedtest_download_bits_per_second Speedtest current Download Speed in bit/s
# TYPE speedtest_download_bits_per_second gauge
speedtest_download_bits_per_second 0.0
# HELP speedtest_upload_bits_per_second Speedtest current Upload speed in bits/s
# TYPE speedtest_upload_bits_per_second gauge
speedtest_upload_bits_per_second 0.0

seems like it is not running. I did add this as you suggested & that got rid of the above error: -e SPEEDTEST_SERVER=31309.

**Comment by MiguelNdeCarvalho** [comment]
Hey,

I will close this, as this should be fixed by now. Feel free to open again if you encounter this again.

Thanks,
MiguelNdeCarvalho
