### ISSUE TITLE
Container keeps restarting

### ISSUE THREAD

**Issue by david7867z** [MiguelNdeCarvalho/speedtest-exporter#71]
Hello,
I am trying to set up an internet-monitor (https://github.com/geerlingguy/internet-monitoring).
I found out, that the container "miguelndecarvalho/speedtest-exporter" is constantly restarting,
after some time i found this error:

```
2021-05-22T09:00:23.237123289Z Current thread 0xb6f42390 (most recent call first):
2021-05-22T09:00:23.237165881Z <no Python frame>
2021-05-22T09:00:51.062463283Z Fatal Python error: init_interp_main: can't initialize time
2021-05-22T09:00:51.068656543Z Python runtime state: core initialized
2021-05-22T09:00:51.068740690Z PermissionError: [Errno 1] Operation not permitted
```

I am running this project on a RaspberryPi 4GB with RaspberryPi OS 64x

I left everything at the default configuration.

Can anyone help me?
Thanks.

**Comment by MiguelNdeCarvalho** [comment]
Hey,

I'm not sure but this can be related to `libseccomp2` version. 
Can you give me the output of `apt info libseccomp2` and `uname -m` please?

Thanks,
MiguelNdeCarvalho

**Comment by david7867z** [comment]
Here is the Output of `apt info libseccomp2` executed on the Pi:
Package: libseccomp2
    Version: 2.3.3-4
    Priority: optional
    Section: libs
    Source: libseccomp
    Maintainer: Kees Cook <kees@debian.org>
    Installed-Size: 161 kB
    Depends: libc6 (>= 2.4)
    Homepage: https://github.com/seccomp/libseccomp
    Download-Size: 33.1 kB
    APT-Manual-Installed: yes
    APT-Sources: http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
    Description: high level interface to Linux seccomp filter
     This library provides a high level interface to constructing, analyzing
     and installing seccomp filters via a BPF passed to the Linux Kernel's
     prctl() syscall.

And here from `uname -m`:
    armv7l

**Comment by MiguelNdeCarvalho** [comment]
Hey,

First of all you are running `Raspberry OS 32 Bits`, you are getting this error because there is a bug on Alpine 3.13. This got fixed on `libseccomp2 2.4.2` and ` Docker 19.03.9`.
Issue: https://github.com/moby/moby/issues/40734
Fix: https://docs.linuxserver.io/faq#libseccomp

Thanks,
MiguelNdeCarvlaho

**Comment by david7867z** [comment]
It works perfectly!
Thank you very much!

**Comment by MiguelNdeCarvalho** [comment]
No problem, that's really good to know that it worked!
