### ISSUE TITLE
Reported speed is not accurate 

### ISSUE THREAD

**Issue by Kl0ven** [MiguelNdeCarvalho/speedtest-exporter#75]
Hi, 
I've encoutered a problem where speeds from the container are not representative of real speeds.

Left term: speeds in docker container
Right term: speeds with speedtest-cli executable running on windows 10
Both of them are running speedtest 1.0.0.2
![compare](https://user-images.githubusercontent.com/11249128/123140335-767bcc00-d457-11eb-83ce-16cbbdb84a98.png)
Also notice this behavior on Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-70-generic x86_64) with Docker version 20.10.2, build 2291f61

![image](https://user-images.githubusercontent.com/11249128/123141662-eb9bd100-d458-11eb-8e29-f3caa4d81b28.png)

Have i messed up something ? or is it expected ?

**Comment by MiguelNdeCarvalho** [comment]
Hey,

First of all this is a really weird issue. I have been running it for almost 5 months and @Doacola too, and both of us didn't get this problem.
Is it possible for you to deploy the container on the Ubuntu machine and then trigger a test? After that install the `Speedtest-CLI` and do a test. If you can send the results here please.

Thanks,
MiguelNdeCarvalho

**Comment by MiguelNdeCarvalho** [comment]
Hey again,

I have tested this on a linode instance.

**speedtest-exporter** 

```bash
24/06/2021 10:31:38 - Server: 10010 | Jitter: 0.01 ms | Ping: 0.955 ms | Download: 5073.59 Mb/s | Upload:1029.03 Mb/s
```

**speedtest-cli**

```bash              
Speedtest by Ookla

Server: fdcservers.net - Frankfurt (id = 10010)
ISP: Linode
Latency:     0.93 ms   (0.05 ms jitter)
Download:  5096.34 Mbps (data used: 3.8 GB)                               
Upload:   995.94 Mbps (data used: 1.6 GB)                               
Packet Loss:     0.0%
Result URL: https://www.speedtest.net/result/c/9831c9dc-27f7-4e1f-b2f3-d5b30aa2faa7
```

Thanks,
MiguelNdeCarvalho

**Comment by Kl0ven** [comment]
hmmm, it's working now, i don't now why 😐. Maybe just a fluke. Thanks for the help anyway, appreciate it 😊

**Comment by MiguelNdeCarvalho** [comment]
Hey,

That's really good to know, sometimes you should see an decrease of the test result, because the server could be doing many tests at the same time. If you get that again feel free to open the issue again.

Thanks,
MiguelNdeCarvalho
