### ISSUE TITLE
Adding speediest-exporter to https://github.com/carlosedp/cluster-monitoring 

### ISSUE THREAD

**Issue by braucktoon** [MiguelNdeCarvalho/speedtest-exporter#85]
Has anyone integrated this speediest-exporter into a https://github.com/carlosedp/cluster-monitoring deployment.
I already have the cluster-monitoring running and working great but struggling to understand how to add the speediest exporter to it.  thanks for any help.

**Comment by MiguelNdeCarvalho** [comment]
Hey,

The guys from @k8s-at-home have made a Helm Chart for it, it should help you. I ahould add this to the documentation. Feel free to ask whatever you need.

Chart: https://github.com/k8s-at-home/charts/tree/master/charts/stable/speedtest-exporter

Thanks,
MiguelNdeCarvalho

**Comment by braucktoon** [comment]
Thank you. I did find that helm chart and installed it. But what else do I need to do?  How can I verify the data is being scraped. Sorry this might be my ignorance of how Prometheus works but I assumed you need to tell Prometheus about the speed test exporter somehow.

**Comment by MiguelNdeCarvalho** [comment]
Hey,

You cam check the logs of the pod to see the logs of scrapes and etc. Yes you are totally write you need to tell Prometheus to scrape the exporter, otherwise it wont know eheh. I think it's better if you join the @k8s-at-home discord.

Thanks,
MiguelNdeCarvalho

**Comment by braucktoon** [comment]
Thanks, I joined over there and asked the question of how to integrate them in the support channel.

**Comment by MiguelNdeCarvalho** [comment]
Yap I saw right now. That's really good to see that you have fixed it with @onedr0p help. I will close the issue but fill free to reopen if needed.
