### ISSUE TITLE
Container health problem

### ISSUE THREAD

**Issue by hitokiri** [MiguelNdeCarvalho/speedtest-exporter#87]
I have the following problem when my raspberry pi works for some time in the container log, this message appears

![image](https://user-images.githubusercontent.com/247528/126930014-5b1e99a4-ba33-43b5-a936-706a37a53888.png)

**Comment by hitokiri** [comment]
`docker ps`
![image](https://user-images.githubusercontent.com/247528/127083612-b435b272-6411-444b-8362-c159e8263433.png)

harware:
raspberry pi 4 8gb 
OS: ubuntu 20.04
```
           speedtest:
  64   │     tty: true
  65   │     stdin_open: true
  66   │     expose:
  67   │       - 9798
  68   │     ports:
  69   │       - 9798:9798
  70   │     image: miguelndecarvalho/speedtest-exporter
  71   │     restart: always
  72   │     networks:
  73   │       - back-tier
```

**Comment by hitokiri** [comment]
`docker ps`
![image](https://user-images.githubusercontent.com/247528/127083612-b435b272-6411-444b-8362-c159e8263433.png)

harware:
raspberry pi 4 8gb 
OS: ubuntu 20.04
```
           speedtest:
  64   │     tty: true
  65   │     stdin_open: true
  66   │     expose:
  67   │       - 9798
  68   │     ports:
  69   │       - 9798:9798
  70   │     image: miguelndecarvalho/speedtest-exporter
  71   │     restart: always
  72   │     networks:
  73   │       - back-tier
```

**Comment by MiguelNdeCarvalho** [comment]
Hey,

Can you do `docker image ls | grep speedtest-exporter` and give me the output please? Did you fix this problem, as you have closed the issue?

Thanks,
MiguelNdeCarvalho
