### ISSUE TITLE
[Docs] Typo in your docs

### ISSUE THREAD

**Issue by Marcel40625** [MiguelNdeCarvalho/speedtest-exporter#90]
Hey there, just an information that there is a typo :)

![21-08-09_08-13-09_423](https://user-images.githubusercontent.com/2056652/128666266-d4b1c914-b011-49c3-b08e-f84a9258a267.png)

**Comment by MiguelNdeCarvalho** [comment]
Hey, 

Really thanks for your help, I will fix it.

Thanks,
MiguelNdeCarvalho
