### ISSUE TITLE
429 Too Many Requests - running in Kubernetes

### ISSUE THREAD

**Issue by madAndroid** [MiguelNdeCarvalho/speedtest-exporter#92]
Hi,

I'm seeing rate limit errors when running this using the `k8s-at-home` chart (located here: https://github.com/k8s-at-home/charts/tree/master/charts/stable/speedtest-exporter) ... I was originally executing from Prometheus every 60 seconds (the default `scrape_interval`) - but even when changing this to be every 20 minutes, I still get the following in the logs:

```
speedtest-exporter-7bdb658f7b-bzk8x speedtest-exporter [2021-09-01 14:51:51.336] [error] Limit reached:
speedtest-exporter-7bdb658f7b-bzk8x speedtest-exporter
speedtest-exporter-7bdb658f7b-bzk8x speedtest-exporter <html>
speedtest-exporter-7bdb658f7b-bzk8x speedtest-exporter <head><title>429 Too Many Requests</title></head>
speedtest-exporter-7bdb658f7b-bzk8x speedtest-exporter <body>
speedtest-exporter-7bdb658f7b-bzk8x speedtest-exporter <center><h1>429 Too Many Requests</h1></center>
speedtest-exporter-7bdb658f7b-bzk8x speedtest-exporter <hr><center>openresty</center>
speedtest-exporter-7bdb658f7b-bzk8x speedtest-exporter </body>
speedtest-exporter-7bdb658f7b-bzk8x speedtest-exporter </html>
speedtest-exporter-7bdb658f7b-bzk8x speedtest-exporter
speedtest-exporter-7bdb658f7b-bzk8x speedtest-exporter 01/09/2021 14:51:51 - Server: 0 | Jitter: 0 ms | Ping: 0 ms | Download: 0.0 Mb/s | Upload:0.0 Mb/s
```

Any suggestions on how to handle this, please? :)

**Comment by madAndroid** [comment]
Probably just a transient issue or something along those lines - seems to be back to normal now - I've adjusted the interval of scraping in Prometheus to be every 60 seconds, and this seems to be okay

**Comment by MiguelNdeCarvalho** [comment]
Hey,

That error is realy weird. I fully recommend you to run scrapes at least every 30 minutes. When running with a scrape interval less then that you can get some errors from Speedtest side. Feel free to open it again if you get those errors again.

Thanks,
MiguelNdeCarvalho
