### ISSUE TITLE
Docker speedtest results are not the same using the speedtest-cli locally 

### ISSUE THREAD

**Issue by Madriax** [MiguelNdeCarvalho/speedtest-exporter#98]
Hello,

I deployed this application on my Home Server using Docker, and the results are slowers using this application rather than using the Speedtest-cli.

Here is a comparison: 
![image](https://user-images.githubusercontent.com/23656170/138316039-04c5d1af-3ebc-4ce4-9031-c16fd7079543.png)

The first line is the output of this speedtest-exporter. I let it ran a few hours and the results are not changing. Bellow the first line, this is the output of the speedtest-cli I just downloaded for the test. You can see there's a huge difference of bandwidth between them. 

--------

I am running on Windows 11 21H2 with Docker version 20.10.7

Docker command to create the container: `docker run -d --name=speedtest-exporter -p 9798:9798 --restart unless-stopped miguelndecarvalho/speedtest-exporter`

**Comment by MiguelNdeCarvalho** [comment]
Hey,

Sorry for the late response, are you running the docker image inside of the Windows machine?

Thanks,
MiguelNdeCarvalho

**Comment by Madriax** [comment]
Hello @MiguelNdeCarvalho 

Yes I am using Docker desktop for Windows

**Comment by MiguelNdeCarvalho** [comment]
Hey,

I'm afraid that I can't help you any further because the docker on Windows should be throttling the testes, that's why you can't get the full speed.

Thanks,
MiguelNdeCarvalho

**Comment by Madriax** [comment]
Hello,

Sorry for the late reply! As you say this is due to Docker on Windows. There's no fix for this.

**Comment by MiguelNdeCarvalho** [comment]
Hey,

@Madriax I am not sure though! Do you have a Linux machine where you can test it?

Thanks,
MiguelNdeCarvalho

**Comment by Madriax** [comment]
I tested on both Linux and Windows again, here are the results:

- **Windows:** Ping=7.9ms Download=152.75Mbps Upload=303.4Mbps

- **Linux:** Ping=7.171ms Download=941.58Mbps Upload=605.66Mbps

**Comment by MiguelNdeCarvalho** [comment]
> I tested on both Linux and Windows again, here are the results:
> 
> - **Windows:** Ping=7.9ms Download=152.75Mbps Upload=303.4Mbps
> 
> - **Linux:** Ping=7.171ms Download=941.58Mbps Upload=605.66Mbps

So in Linux we have the real values, correct?

**Comment by Madriax** [comment]
Yes exactly !

**Comment by MiguelNdeCarvalho** [comment]
I think there is nothing we can do about it! That should be related to the Windows network used by docker containers
